[package]
name = "rust-dynamic-flows"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.6.3"
num-traits = "0.2.15"
ordered-float = "3.7.0"
itertools = "0.11.0"
plotters = "0.3.5"
